name: generex
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: none
# repository: https://github.com/YassineDabbous/dart-generex

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.4.2
  dart_style: ^2.3.6
  recase: ^4.1.0
  intl: ^0.19.0
  
  # not required, used for local test
  core:
    path: ./libraries/core
  concrete:
    path: ./libraries/concrete

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.4.10
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
